apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-scale-robot

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: scale-apps
  namespace: default
rules:
  - apiGroups: ["apps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
    resources: ["deployments"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: scale-apps-auto-scale-robot
  namespace: default
roleRef:
  kind: Role
  name: scale-apps
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: auto-scale-robot
    namespace: default