apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-auto-scaler-deployment
  labels:
    app: selenium-auto-scaler
    name: selenium-auto-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-auto-scaler
  template:
    metadata:
      labels:
        app: selenium-auto-scaler
    spec:
      containers:
        - name: selenium-auto-scaler
          image: selenium-auto-scaler
          imagePullPolicy: Never
          env:
            - name: SCHEDULER_UP_CRON
              value: "* 57 6 * * ?"
            - name: SCHEDULER_DOWN_CRON
              value: "* 02 7 * * ?"
            - name: USER_REQUEST_IP
              value: "1"
            - name: USER_REQUEST_PORT
              value: "90"
            - name: HUB_IP
              value: "selenium-hub-service-clusterip.default.svc.cluster.local"
            - name: HUB_PORT
              value: "4444"
            - name: DEFAULT_SCALE
              value: "2"
            - name: NAMESPACE
              value: "default"
            - name: DEPLOYMENT
              value: "selenium-auto-scaler-deployment"
            - name: MAX_SCALE
              value: "4"
          ports:
            - containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: selenium-auto-scaler-nodeport
  labels:
    name: selenium-auto-scaler
    service: selenium-auto-scaler-nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: selenium-auto-scaler