apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service-nodeport
  labels:
    name: selenium-hub
    service: selenium-hub-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 4444
  selector:
    app: selenium-hub